void display_menu();
void display_temperature_menu();
void display_distance_menu();
void display_weight_menu();
int kelvin_to_fahrenheit(int kelvin);
int kelvin_to_celsius(int kelvin);
int fahrenheit_to_kelvin(int fahrenheit);
int fahrenheit_to_celsius(int fahrenheit);
int celsius_to_kelvin(int celsius);
int celsius_to_fahrenheit(int celsius);